<?php
/**
 * Copyright 2013 Adobe
 * All Rights Reserved.
 */

/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var View $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Sales\Block\Adminhtml\Order\Comments\View;

$entityId = $block->getEntity()->getId();
$editCommentCheck = $block->getData('editCommentCheck');

/** @var \Vapewholesaleusa\MageWorxOrderEditor\ViewModel\Comments $viewModel */
$viewModel = $block->getData('view_model')

?>
<?php if ($_entity = $block->getEntity()): ?>
    <div id="comments_block" class="edit-order-comments">
        <div class="order-history-block">
            <div class="admin__field field-row">
                <label class="admin__field-label"
                       for="history_comment"><?= $escaper->escapeHtml(__('Comment Text')) ?></label>
                <div class="admin__field-control">
                <textarea name="comment[comment]"
                          rows="3"
                          cols="5"
                          id="history_comment"
                          data-wysiwyg-initialize="1"
                          class="admin__control-textarea"></textarea>
                </div>
            </div>
            <div class="admin__field">
                <div class="order-history-comments-options">
                    <?php if ($block->canSendCommentEmail()): ?>
                        <div class="admin__field admin__field-option">
                            <input name="comment[is_customer_notified]"
                                   type="checkbox"
                                   class="admin__control-checkbox"
                                   id="history_notify"
                                   value="1" />
                            <label class="admin__field-label"
                                   for="history_notify"><?= $escaper->escapeHtml(__('Notify Customer by Email')) ?></label>
                        </div>
                    <?php endif; ?>
                    <div class="admin__field admin__field-option">
                        <input name="comment[is_visible_on_front]"
                               type="checkbox"
                               id="history_visible"
                               class="admin__control-checkbox"
                               value="1" />
                        <label class="admin__field-label"
                               for="history_visible"> <?= $escaper->escapeHtml(__('Visible on Storefront')) ?></label>
                    </div>
                </div>
                <div class="order-history-comments-actions">
                    <?= $block->getChildHtml('submit_button') ?>
                </div>
            </div>
        </div>

        <ul class="note-list" id="mw-oe-notes">
            <?php foreach ($_entity->getCommentsCollection(true) as $comment): ?>
                <li class="note-list-item">
                <span class="note-list-date">
                    <?= /* @noEscape */ $block->formatDate($comment->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                </span>
                    <span class="note-list-time">
                    <?= /* @noEscape */ $block->formatTime($comment->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                </span>
                    <span class="note-list-customer">
                    <?= $escaper->escapeHtml(__('Customer')) ?>
                        <?php if ($comment->getIsCustomerNotified()): ?>
                            <span class="note-list-customer-notified"><?= $escaper->escapeHtml(__('Notified')) ?></span>
                        <?php else: ?>
                            <span class="note-list-customer-not-notified">
                            <?= $escaper->escapeHtml(__('Not Notified')) ?>
                        </span>
                        <?php endif; ?>
                </span>
                    <?php if ($editCommentCheck->isCommentAllowedToEdit($comment)): ?>
                        <span class="note-list-customer">
                        <a class="edit_comment" href="#">
                            <?= $escaper->escapeHtml(__('Edit')) ?>
                        </a>
                    </span>
                        <div class="edit-comment-container" style="display: none">
                            <div class="admin__field-control">
                                <label>
                                <textarea name="edit_comment" class="edit-comment-textarea admin__control-textarea"
                                          disabled="disabled" rows="3" cols="5" spellcheck="false"
                                          data-wysiwyg-initialize="1"
                                          data-comment-id="<?= $block->escapeHtmlAttr($comment->getId())?>"
                                          id="mw-oe-edit-comment-<?= $block->escapeHtmlAttr($comment->getId())?>">
                                    <?= /* @noEscape */ nl2br($escaper->escapeHtml(
                                        $viewModel->replaceComment($comment->getComment()),
                                        [
                                            "a", "b", "strong", "h1", "h2", "h3", "h4", "h5", "br", "em", "hr", "i",
                                            "li", "ol", "p", "s", "span", "table", "tbody", "tr", "td", "u", "ul"
                                        ]
                                    ))?>
                                </textarea>
                                </label>
                            </div>
                            <div class="order-history-comments-actions">
                                <button title="Update Comment" type="button" class="action-secondary edit-comment-submit"
                                        data-comment-id="<?= $escaper->escapeHtmlAttr($comment->getId()); ?>">
                                    <?= $escaper->escapeHtml(__('Update Comment')) ?>
                                </button>
                                <button title="Cancel" type="button" class="edit-comment-cancel">
                                    <?= $escaper->escapeHtml(__('Cancel')) ?>
                                </button>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="note-list-comment">

                        <?= /* @noEscape */ nl2br($escaper->escapeHtml(
                            $viewModel->replaceComment($comment->getComment()),
                            [
                                "a", "b", "strong", "h1", "h2", "h3", "h4", "h5", "br", "em", "hr",
                                "i", "li", "ol", "p", "s", "span", "table", "tbody", "tr", "td", "u", "ul"
                            ]
                        ))?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php $scriptString = <<<script
require(['prototype'], function(){
    submitComment = function() {
        submitAndReloadArea($('comments_block').parentNode, '{$escaper->escapeJs($block->getSubmitUrl())}')
    };
    if ($('submit_comment_button')) {
        $('submit_comment_button').observe('click', submitComment);
    }
});
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onclick',
        "openModal(event); event.preventDefault();",
        'a.edit_comment'
    ) ?>

    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onclick',
        "closeCommentArea();",
        '.edit-comment-cancel'
    ) ?>

    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onclick',
        "updateComment('".$escaper->escapeHtml($editCommentCheck->getEditUrl($entityId))."', event);",
        '.edit-comment-submit'
    ) ?>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {


        $('#mw-oe-notes .note-list-item').each(function () {
            let $note = $(this),
                $editWrapper = $note.find('.edit-comment-wrapper'),
                $editContent = $editWrapper.find('.mw-oe-note-edit-content'),
                $editButton = $editWrapper.find('.block-edit-link'),
                $submitButton = $editContent.find('.mw-oe-notes-edit-submit'),
                $textarea = $editContent.find('.mw-oe-note-edit-new-text'),
                $oldComment = $note.find('.note-list-comment');

            $textarea.on('change', function (event) {
                $oldComment.html($(event.target).val());
            });

            $editButton.on('click', function (event) {
                event.preventDefault();
                $editContent.toggle();
                $editButton.toggle();
            });

            $submitButton.on('click', function (event) {
                event.preventDefault();
                $editButton.toggle();
                $editContent.toggle();
            });
        });
    });
</script>

<?= /* @noEscape */ $block->getChildHtml('comments_js') ?>
