<?php
/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="reports-content">
    <?php echo $block->getChildHtml('grid.filter.form.commissions') ?>
</div>
<?php echo $block->getGridHtml() ?>

<?= $secureRenderer->renderTag('script', ['type' => 'text/javascript'], "
    require([
        'jquery',
        'mage/backend/validation',
        'prototype'
    ], function(jQuery){
        jQuery('#filter_form').mage('validation', {errorClass: 'mage-error'});

        function filterFormSubmit() {
            var filters = $$('#filter_form input', '#filter_form select');
            var elements = [];
            for (var i in filters) {
                if (filters[i].value && filters[i].value.length && !filters[i].disabled) {
                    elements.push(filters[i]);
                }
            }
            if (jQuery('#filter_form').valid()) {
                setLocation('" . $block->escapeHtml($block->getFilterUrl()) . "filter/' + Base64.encode(Form.serializeElements(elements)) + '/');
            }
        }

        window.filterFormSubmit = filterFormSubmit;
    });
", false) ?>
